### ISSUE TITLE
Add HVIL shutdown relay

### ISSUE THREAD

**Issue by GuySmily** [spartanracingelectric/SRE-2#31]
~~Pin 132 to NC relay, open relay to cut power e.g. upon loss of BMS communication~~

**Comment by chucktesta154k** [comment]
should this be NO for safety? or it can be NC because it isn't required

Charlie Trevaskis
San Jose State University
Mechanical Engineering Department
Spartan Racing Electric | Chief Engineer
(209) 217-6427
CharlieTrevaskis@gmail.com <charlietrevaskis@gmail.com>
http://www.spartanracingelectric.com

**Comment by guill0tine** [comment]
Yea for safety, we should be going with the NO relay. But rules don't care as its not required in the HVIL loop.

**Comment by GuySmily** [comment]
Pin 132 connected to NO relay.
On VCU startup: Set Pin 132 = ??
On HVIL Term Sense == high: Set Pin 132 = ??
----
If ??? (e.g. > #ms since last BMS CAN message), set pin low
If ???, set pin high again?

**Comment by GuySmily** [comment]
Duplicate of #9

**Comment by GuySmily** [comment]
Pin 132 = IO_DO_01
