### ISSUE TITLE
decode rinehart can messages

### ISSUE THREAD

**Issue by chucktesta154k** [spartanracingelectric/SRE-2#6]
Need to be able to decode can messages from the rinehart

**Comment by chucktesta154k** [comment]
Why is this closed? Are we considering this using pcan? The vcu needs to be able to take can messages and save the values of variables accordingly.

**Comment by vinayponnaganti** [comment]
Oh, I considered it closed because we are able to read the values from the
vcu and take actions accordingly all in the vcu (such as enable lockout
when disabled and vice versa)

**Comment by vinayponnaganti** [comment]
*Read values from the rinehart
