### ISSUE TITLE
Elcon CAN rate is 250 baud, will have to program the BMS to also work at 250 baud.

### ISSUE THREAD

**Issue by rabeelio** [spartanracingelectric/SRE-2#64]
Seems that whenever we need to charge up, we need to switch the BMS can rate to 250. CAN rate cannot be changed on Elcon charger.

http://lithiumate.elithion.com/php/controller_can_specs.php
http://lithiumate.elithion.com/php/elcon.php

**Comment by alexsternberg** [comment]
We shouldn't need to change the speed for charging. I believe Rusty went back and traded in our 250kbps transceiver for a 500kbps one.

**Comment by chucktesta154k** [comment]
Yep. We have the 500 can module now.

**Comment by rabeelio** [comment]
fsho
