### ISSUE TITLE
BMS Fan Control

### ISSUE THREAD

**Issue by rabeelio** [spartanracingelectric/SRE-2#73]
VCU Input: BMS temperature CAN message

Output: Drive fans on/off

**Comment by GuySmily** [comment]
23C = room temperature
30-40C: turn fans on
60C = maximum allowed cell temperature per rules
BMBs rated +/- 2C

**Comment by rabeelio** [comment]
done

**Comment by GuySmily** [comment]
I want to remember to test this, so let's try these Testing labels I created and not close issues until testing is complete.  Not sure how the pros track this stuff without external tools..
